<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqx24W3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqx24W3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUqx24W3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUqx24W3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUqx24W3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uqx24W3',
    'container.build_id' => 'a8bbddad',
    'container.build_time' => 1620680839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqx24W3');
