<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'products_list' => [[], ['_controller' => 'App\\Controller\\APICatalogController::listAllProduct'], [], [['text', '/api/products']], [], []],
    'getProduct' => [['productId'], ['_controller' => 'App\\Controller\\APICatalogController::getProduct'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/product']], [], []],
    'ModifieProduct' => [['id'], ['_controller' => 'App\\Controller\\APICatalogController::ModifieProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/product']], [], []],
    'NouveauProduit' => [[], ['_controller' => 'App\\Controller\\APICatalogController::addProduct'], [], [['text', '/api/product']], [], []],
    'delProduct' => [['productId'], ['_controller' => 'App\\Controller\\APICatalogController::delProduct'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/product']], [], []],
    'order' => [['orderId'], ['_controller' => 'App\\Controller\\APIOrderController::getSpecificOrder'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/order']], [], []],
    'orderAll' => [[], ['_controller' => 'App\\Controller\\APIOrderController::getOrder'], [], [['text', '/api/orders']], [], []],
    'getCart' => [[], ['_controller' => 'App\\Controller\\APIShoppingCartController::getCart'], [], [['text', '/api/cart']], [], []],
    'addCart' => [['productId'], ['_controller' => 'App\\Controller\\APIShoppingCartController::addShoppingCart'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/cart']], [], []],
    'deleteCart' => [['productId'], ['_controller' => 'App\\Controller\\APIShoppingCartController::delShoppingCart'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/cart']], [], []],
    'delCart' => [[], ['_controller' => 'App\\Controller\\APIShoppingCartController::validate'], [], [['text', '/api/cart/validate']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/api/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], []],
    'Register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/api/register']], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegisterController::verifyUserEmail'], [], [['text', '/verifyEmail']], [], []],
    'TestApi' => [[], ['_controller' => 'App\\Controller\\TestController::show123'], [], [['text', '/api/posts']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login']], [], []],
];
