<?php

namespace ContainerUqx24W3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TQPxKGsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TQPxKGs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TQPxKGs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serialize' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'serialize' => '?',
        ]);
    }
}
