<?php

namespace ContainerVLxegqn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAPIUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\APIUserController' shared autowired service.
     *
     * @return \App\Controller\APIUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'APIUserController.php';

        return $container->services['App\\Controller\\APIUserController'] = new \App\Controller\APIUserController();
    }
}
